import { readdirSync, readFileSync, existsSync, mkdirSync, copyFileSync } from "fs";
import { execSync } from "child_process";
import sharp from "sharp";
import { join, relative, basename, extname } from "path";
import taskLists from "markdown-it-task-lists";
import markdownItContainer from "markdown-it-container";
import markdownItAttrs from "markdown-it-attrs";
import markdownItFootnote from "markdown-it-footnote";
import pluginRss from "@11ty/eleventy-plugin-rss";
import Image from "@11ty/eleventy-img";
import {
  loadSiteConfig,
  resolveSiteName,
} from "./scripts/utils/config-loader.js";
import { formatDate } from "./scripts/utils/format-date.js";

// Auto-discover magic machines from lib/magic-machines/
// Each machine needs a manifest.json with a "route" field and an app.entry path.
function loadMagicMachines() {
  const dir = "lib/magic-machines";
  if (!existsSync(dir)) return [];

  return readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => {
      const manifestPath = join(dir, d.name, "manifest.json");
      if (!existsSync(manifestPath)) return null;
      const manifest = JSON.parse(readFileSync(manifestPath, "utf-8"));
      return { dirName: d.name, ...manifest };
    })
    .filter((m) => m && m.route && m.app?.entry);
}

// Auto-discover visualizer packages from lib/visualizers/
async function loadVisualizers() {
  const dir = "lib/visualizers";
  if (!existsSync(dir)) return [];

  const folders = readdirSync(dir, { withFileTypes: true })
    .filter((d) => d.isDirectory())
    .map((d) => d.name);

  const visualizers = [];
  for (const name of folders) {
    const indexPath = join(dir, name, "index.js");
    if (existsSync(indexPath)) {
      const mod = await import(`./${indexPath}`);
      visualizers.push({ name, ...mod });
    }
  }
  return visualizers;
}

export default async function (eleventyConfig) {
  // Per-site src directory (set by dev-local.js / build-site.js; falls back to "src" for CI)
  const SRC = process.env.SRC_DIR
    ? relative(process.cwd(), process.env.SRC_DIR)
    : "src";

  // Load site configuration
  const siteName = resolveSiteName();
  const siteConfig = await loadSiteConfig(siteName, {
    contentDir: process.env.CONTENT_DIR,
  });

  // Load visualizer modules for build-time transforms
  const visualizers = await loadVisualizers();
  // RSS feed plugin (provides dateToRfc3339, htmlToAbsoluteUrls, etc.)
  eleventyConfig.addPlugin(pluginRss);

  // Don't use .gitignore for Eleventy's ignore rules
  // (src/content/ is gitignored since it's generated, but Eleventy must process it)
  eleventyConfig.setUseGitIgnore(false);

  // Pass through static assets
  eleventyConfig.addPassthroughCopy(`${SRC}/assets`);
  // Media files — serve at /media/ (covers optimized/ subdirectory and any media-folder files)
  eleventyConfig.addPassthroughCopy({ [`${SRC}/media`]: "media" });
  // Vault attachment files at vault-relative paths outside src/media/
  // (e.g. src/projects/diagram.html → _site/projects/diagram.html)
  // templateFormats: ["md", "njk"] (set below) excludes .html from Eleventy's page pipeline entirely —
  // no output directory, no collection entry. Passthrough-copy handles .html files. Themes use .njk only.
  eleventyConfig.addPassthroughCopy(`${SRC}/**/*.{jpg,jpeg,png,gif,webp,svg,pdf,mp4,webm}`);
  eleventyConfig.addPassthroughCopy(`${SRC}/**/*.html`);
  // OG preview images — serve at /og/ (separate from /media/ to avoid optimization)
  eleventyConfig.addPassthroughCopy({ [`${SRC}/og`]: "og" });
  // Graph data — always generated by preprocessor, served at /graph.json
  eleventyConfig.addPassthroughCopy({ [`${SRC}/graph.json`]: "graph.json" });
  // Graph settings — vault defaults from .bloob/graph.yaml, served at /graph-settings.json
  eleventyConfig.addPassthroughCopy({
    [`${SRC}/graph-settings.json`]: "graph-settings.json",
  });
  // Tag index — served at /tagIndex.json for the tags visualizer (runtime fetch)
  eleventyConfig.addPassthroughCopy({
    [`${SRC}/_data/tagIndex.json`]: "tagIndex.json",
  });
  // Favicons — generated at build time by scripts/generate-favicons.js into src/
  eleventyConfig.addPassthroughCopy({ [`${SRC}/favicon.png`]: "favicon.png" });
  eleventyConfig.addPassthroughCopy({
    [`${SRC}/apple-touch-icon.png`]: "apple-touch-icon.png",
  });

  // Magic machines — auto-discovered from lib/magic-machines/*/manifest.json
  // Gated by features.magic_machines in sites/*.yaml (defaults to true when absent).
  if (siteConfig.features?.magic_machines !== false) {
    const magicMachines = loadMagicMachines();
    for (const machine of magicMachines) {
      // Copy entire app/ directory so vendor assets and subdirs are included alongside index.html
      const appDir = `lib/magic-machines/${machine.dirName}/app/`;
      const destDir = machine.route.replace(/^\//, "");
      eleventyConfig.addPassthroughCopy({ [appDir]: destDir });
    }
    // Legacy alias — scene-nav-builder was previously served at /tools/ before
    // the /magic-machine/ convention was established. Keep old URL working.
    eleventyConfig.addPassthroughCopy({
      "lib/magic-machines/scene-nav-builder/app/": "tools/scene-nav-builder/",
    });
    // Cloudflare Pages _headers — COOP/COEP for magic machines requiring SharedArrayBuffer
    if (existsSync("lib/magic-machines/_headers")) {
      eleventyConfig.addPassthroughCopy({ "lib/magic-machines/_headers": "_headers" });
    }
  }

  // Watch for changes during development
  eleventyConfig.addWatchTarget(`${SRC}/assets/`);
  eleventyConfig.addWatchTarget("lib/");

  // Don't watch binary attachment files — large files synced by iCloud/Dropbox cause rebuild loops
  // Covers both src/media/ (old flat layout) and vault-structure paths throughout src/
  eleventyConfig.watchIgnores.add(`${SRC}/media/**`);
  eleventyConfig.watchIgnores.add(`${SRC}/**/*.{jpg,jpeg,png,gif,pdf,mp4,webm}`);
  eleventyConfig.watchIgnores.add(`${SRC}/og/**`);
  eleventyConfig.watchIgnores.add(".cache/**");

  // Capture md library reference for use in filters below.
  let mdLib;
  eleventyConfig.amendLibrary("md", (lib) => { mdLib = lib; });

  // | md — render a frontmatter string as a markdown block (wraps in <p>)
  // | mdinline — render inline markdown without the <p> wrapper (for use inside headings etc.)
  // Both are safe for use with | safe in templates.
  eleventyConfig.addFilter("md", (str) => mdLib ? mdLib.render(String(str || "")) : str);
  eleventyConfig.addFilter("mdinline", (str) => mdLib ? mdLib.renderInline(String(str || "")) : str);

  // Single line breaks → <br> by default (matches Obsidian behavior).
  // Opt out per-site with features: { soft_breaks: false } in _bloob-settings.md.
  eleventyConfig.amendLibrary("md", (mdLib) => {
    mdLib.set({ linkify: true });
    if (siteConfig.features?.soft_breaks !== false) {
      mdLib.set({ breaks: true });
    }
    mdLib.use(markdownItFootnote);
    mdLib.use(taskLists, { enabled: false, label: true });
    // {.class} {#id} {attr=value} attribute syntax on links, images, headings
    // e.g. [CONTACT US](#footer){.button} → <a href="#footer" class="button">
    mdLib.use(markdownItAttrs);

    // ::: name [key=value ...] — section containers for styling and visualizers.
    // First word = CSS class. Additional key=value pairs → data-vis-settings JSON.
    // Examples:
    //   ::: bg-dark                        → <section class="bg-dark">
    //   ::: image-grid title="Our Team"    → <section class="image-grid" data-vis-settings='{"title":"Our Team"}'>
    // Backwards compatible — single-word fences are unchanged.
    mdLib.use(markdownItContainer, "section", {
      validate: () => true,
      render(tokens, idx) {
        if (tokens[idx].nesting !== 1) return `</section>\n`;
        const info = tokens[idx].info.trim();
        const spaceIdx = info.indexOf(" ");
        if (spaceIdx === -1) {
          return `<section class="${info}">\n`;
        }
        const cls = info.slice(0, spaceIdx);
        const settingsStr = info.slice(spaceIdx + 1).trim();
        const settings = {};
        const kvPattern = /([\w-]+)=(?:"([^"]*)"|([\S]*))/g;
        let m;
        while ((m = kvPattern.exec(settingsStr)) !== null) {
          settings[m[1]] = m[2] !== undefined ? m[2] : m[3];
        }

        // _raw is injected by inject-container-raw.js during preprocessing.
        // Decode it and emit as data-vis-raw so build-time visualizer transforms
        // can parse raw markdown instead of rendered HTML — keeping parser.js
        // shareable across Eleventy, browser preview, and Obsidian plugin.
        const rawBase64 = settings._raw;
        delete settings._raw;
        const rawAttr = rawBase64
          ? ` data-vis-raw="${rawBase64}"`
          : "";

        const settingsAttr = Object.keys(settings).length
          ? ` data-vis-settings='${JSON.stringify(settings)}'`
          : "";
        return `<section class="${cls}"${settingsAttr}${rawAttr}>\n`;
      },
    });
  });

  // Date formatting filter — see scripts/utils/format-date.js.
  // Handles Date objects, YYYY-MM-DD strings, and arrays (e.g. `date_updated`,
  // for which the most recent entry is shown regardless of list order).
  eleventyConfig.addFilter("dateFormat", formatDate);

  // Truncate filter (Hugo has this built-in)
  eleventyConfig.addFilter("truncate", function (str, len) {
    if (!str) return "";
    if (str.length <= len) return str;
    return str.slice(0, len) + "…";
  });

  // Head filter — take first N items from array (like Hugo's `first`)
  eleventyConfig.addFilter("head", function (array, n) {
    if (!Array.isArray(array)) return [];
    return array.slice(0, n);
  });

  // Convert \n newlines to <br> — used for multi-line bylines
  eleventyConfig.addFilter("nl2br", function (str) {
    if (!str) return "";
    return String(str).replace(/\n/g, "<br>");
  });

  // Render markdown-style links [text](url) → <a href="url">text</a>
  // External URLs (https?://) open in a new tab; bare paths are treated as internal.
  eleventyConfig.addFilter("mdLinks", function (str) {
    if (!str) return "";
    return String(str).replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, text, url) => {
      const isExternal = /^https?:\/\//.test(url);
      const attrs = isExternal
        ? `href="${url}" target="_blank" rel="noopener"`
        : `href="${url}"`;
      return `<a ${attrs}>${text}</a>`;
    });
  });

  // Capitalize filter
  eleventyConfig.addFilter("capitalize", function (str) {
    if (!str) return "";
    return str.charAt(0).toUpperCase() + str.slice(1);
  });

  // Split filter — splits a string by a delimiter, returns array
  eleventyConfig.addFilter("split", function (str, delimiter) {
    if (!str) return [];
    return String(str).split(delimiter);
  });

  // Title case filter — matches Hugo's .Title behavior (lowercase small words)
  // Also converts hyphens to spaces for slugified strings
  eleventyConfig.addFilter("titleCase", function (str) {
    if (!str) return "";
    const small = new Set([
      "a",
      "an",
      "and",
      "as",
      "at",
      "but",
      "by",
      "for",
      "in",
      "nor",
      "of",
      "on",
      "or",
      "so",
      "the",
      "to",
      "up",
    ]);
    return str
      .replace(/-/g, " ")
      .split(" ")
      .map((word, i) => {
        if (i > 0 && small.has(word.toLowerCase())) return word.toLowerCase();
        return word.charAt(0).toUpperCase() + word.slice(1);
      })
      .join(" ");
  });

  // Filter out system/reserved tags from display
  function filterTagList(tags) {
    return (tags || []).filter(
      (tag) => !["all", "nav", "posts", "not-for-public"].includes(tag),
    );
  }
  eleventyConfig.addFilter("filterTagList", filterTagList);

  // Slugify filter for tag URLs
  eleventyConfig.addFilter("slugify", function (str) {
    if (!str) return "";
    return str
      .toLowerCase()
      .replace(/[^a-z0-9\s/-]/g, "")
      .replace(/\s+/g, "-")
      .replace(/-+/g, "-")
      .replace(/^-|-$/g, "");
  });

  // HTML content extraction filters — useful for themes that need to separate
  // heading, images, and body text into distinct layout regions at build time.

  // Returns the raw HTML of the first <h1> element in a rendered content string.
  eleventyConfig.addFilter("extractFirstH1", function (content) {
    if (!content) return "";
    const match = content.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);
    return match ? match[0] : "";
  });

  // Returns content with the first <h1> element removed.
  eleventyConfig.addFilter("stripFirstH1", function (content) {
    if (!content) return "";
    return content.replace(/<h1[^>]*>[\s\S]*?<\/h1>/i, "");
  });

  // Returns an array of raw <img> HTML strings found in a rendered content string.
  eleventyConfig.addFilter("extractImages", function (content) {
    if (!content) return [];
    const matches = content.match(/<img[^>]*>/gi) || [];
    return matches;
  });

  // Returns content with all <img> tags removed, plus any now-empty <p> wrappers.
  eleventyConfig.addFilter("stripImages", function (content) {
    if (!content) return "";
    return content
      .replace(/<img[^>]*>/gi, "")
      .replace(/<p>\s*<\/p>/gi, "");
  });

  // Position-aware variants: only operate on images that appear BEFORE the first <h1>.
  // Use these in layouts that want to separate hero images (above the title) from
  // body images (below the title, rendered as normal inline content).

  // Returns an array of raw <img> HTML strings found BEFORE the first <h1>.
  eleventyConfig.addFilter("extractHeroImages", function (content) {
    if (!content) return [];
    const h1Index = content.search(/<h1[\s>]/i);
    const region = h1Index >= 0 ? content.slice(0, h1Index) : content;
    return region.match(/<img[^>]*>/gi) || [];
  });

  // Returns content with pre-<h1> <img> tags removed (and empty <p> wrappers cleaned up).
  // Images that appear AFTER the first <h1> are left intact for inline body rendering.
  eleventyConfig.addFilter("stripHeroImages", function (content) {
    if (!content) return "";
    const h1Index = content.search(/<h1[\s>]/i);
    if (h1Index < 0) return content;
    const before = content
      .slice(0, h1Index)
      .replace(/<img[^>]*>/gi, "")
      .replace(/<p>\s*<\/p>/gi, "");
    return before + content.slice(h1Index);
  });

  // Collection of all unique tags (for tag page pagination)
  eleventyConfig.addCollection("tagList", function (collectionApi) {
    const tagSet = new Set();
    collectionApi.getAll().forEach((item) => {
      (item.data.tags || []).forEach((tag) => tagSet.add(tag));
    });
    return filterTagList([...tagSet]).sort();
  });

  // Auto-detect sections from content directory structure
  // Mirrors Hugo's .Site.Sections behavior
  // Excludes non-content directories (media, assets, tags, etc.)
  const RESERVED_DIRS = new Set(["media", "assets", "tags", "pagefind", "og", "search"]);

  eleventyConfig.addCollection("sections", function (collectionApi) {
    const sections = new Set();
    collectionApi.getAll().forEach((item) => {
      const parts = item.url.split("/").filter(Boolean);
      if (parts.length > 1 && !RESERVED_DIRS.has(parts[0])) {
        sections.add(parts[0]);
      }
    });
    return [...sections].sort();
  });

  // Dynamic per-section collections
  // Auto-discovers top-level content folders in src/ and registers a collection for each.
  // Each section gets its own top-level addCollection call (Eleventy doesn't support
  // registering collections inside another collection callback — they resolve too late).
  // Collection names are camelCased from folder slugs (e.g., "lists-of-favorites" → "listsOfFavorites").
  const srcDirs = readdirSync(SRC, { withFileTypes: true })
    .filter((d) => d.isDirectory() && !RESERVED_DIRS.has(d.name) && !d.name.startsWith("_"))
    .map((d) => d.name);

  for (const section of srcDirs) {
    const collectionName = section.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
    eleventyConfig.addCollection(collectionName, function (collectionApi) {
      return collectionApi.getAll()
        .filter((item) => {
          const parts = item.url.split("/").filter(Boolean);
          return parts.length > 1 && parts[0] === section;
        })
        .sort((a, b) => (b.date || 0) - (a.date || 0));
    });
  }

  // Backlinks: compute which pages link to each other
  // Uses addCollection to attach backlinks data to each page.
  // Reads source files from disk (stable API, not Eleventy internals).
  if (siteConfig.features?.backlinks !== false)
    eleventyConfig.addCollection("withBacklinks", function (collectionApi) {
      const all = collectionApi.getAll();

      // Extract internal links from markdown source (exclude images)
      function extractLinks(source) {
        const links = [];
        // Markdown links [text](url) — exclude images ![alt](url)
        const mdLinks = source.matchAll(/(?<!!)\[([^\]]*)\]\(([^)]+)\)/g);
        for (const m of mdLinks) {
          const url = m[2];
          // Only internal links (starting with /)
          if (url.startsWith("/") && !/\.(jpg|jpeg|png|gif|webp|svg|pdf|mp4|webm|html)$/i.test(url)) {
            links.push(url.replace(/\/$/, "")); // normalize trailing slash
          }
        }
        return links;
      }

      // First pass: build a map of page URL → outgoing links
      const linkMap = new Map();
      for (const page of all) {
        if (!page.inputPath.endsWith(".md")) continue;
        try {
          const source = readFileSync(page.inputPath, "utf-8");
          linkMap.set(page.url.replace(/\/$/, ""), extractLinks(source));
        } catch {
          // File may not exist if it's a generated page
        }
      }

      // Second pass: for each page, find all pages that link TO it
      for (const page of all) {
        const pageUrl = page.url.replace(/\/$/, "");
        page.data.backlinks = all
          .filter((other) => {
            if (other.url === page.url) return false;
            const otherUrl = other.url.replace(/\/$/, "");
            const outgoing = linkMap.get(otherUrl);
            return outgoing?.includes(pageUrl);
          })
          .map((p) => ({ url: p.url, title: p.data.title }));
      }

      return all;
    });

  // Image optimization transform
  // Finds <img src="/media/..."> in rendered HTML, generates WebP + original
  // at reasonable sizes, replaces with <picture> element.
  // Only /media/ paths are optimized — everything in /media/ is user content
  // (including nested folders). OG images live at /og/ and are never touched.
  const mediaConfig = siteConfig.media || {};
  // Persistent image cache: write optimized images to src/media/optimized/ so they survive
  // _site/ being cleaned between builds. The { "src/media": "media" } passthrough copy handles
  // serving them. On first encounter sharp processes the image; subsequent builds skip sharp
  // entirely (passthrough already copied the cached file to _site/media/optimized/).
  const MEDIA_CACHE_DIR = `${SRC}/media/optimized`;

  if (mediaConfig.optimize !== false)
    eleventyConfig.addTransform("optimizeImages", async function (content) {
      if (!this.page.outputPath?.endsWith(".html")) return content;

      const imgRegex = /<img\s+([^>]*?)src="(\/[^"]+\.(?:jpg|jpeg|png|gif|webp|svg))"([^>]*?)>/gi;
      const matches = [...content.matchAll(imgRegex)];
      if (matches.length === 0) return content;

      let result = content;
      for (const match of matches) {
        const [originalTag, before, src, after] = match;

        const inputPath = join(SRC, decodeURIComponent(src));
        if (!existsSync(inputPath)) continue;

        // ── Image opt-out flags (checked via class or attribute on the <img>) ──────
        // no-optimize  → skip entirely, serve original file at full resolution
        // no-zoom      → optimize to 500px-tall webp, no PhotoSwipe (use for logos/nav)
        // no-lightbox  → optimize to display size, no PhotoSwipe (banner images)
        // no-pswp      → optimize normally, skip PhotoSwipe (inside Swiper etc.)
        // ─────────────────────────────────────────────────────────────────────────

        // Hidden images (OG/pagefind meta): leave untouched — wrapping in <a> would make them visible.
        if ((before + after).includes("hidden")) continue;

        // no-optimize: skip ALL processing — leave original <img> tag unchanged.
        // Ensure the src is properly URL-encoded so browsers can load files with spaces.
        // Example: ![alt](image.png){.no-optimize}
        if ((before + after).includes("no-optimize")) {
          const encodedSrc = src.split("/").map(part => encodeURIComponent(decodeURIComponent(part))).join("/");
          if (encodedSrc !== src) {
            result = result.replace(originalTag, originalTag.replace(`src="${src}"`, `src="${encodedSrc}"`));
          }
          continue;
        }

        // Banner/UI images (no-lightbox): optimize to reasonable display size, no PhotoSwipe.
        // Used for bloob-object banner images — full quality but no lightbox wrapper.
        if ((before + after).includes("no-lightbox")) {
          const ext = src.toLowerCase().split(".").pop();
          if (ext === "gif") continue;
          try {
            const siteOptDir = join(outputDir, "media/optimized");
            mkdirSync(siteOptDir, { recursive: true });
            mkdirSync(MEDIA_CACHE_DIR, { recursive: true });
            const baseName = decodeURIComponent(src.split("/").pop().replace(/\.[^.]+$/, ""));
            const cacheFile = join(MEDIA_CACHE_DIR, `${baseName}-banner.webp`);
            const outFile = join(siteOptDir, `${baseName}-banner.webp`);
            const outUrl = `/media/optimized/${encodeURIComponent(baseName)}-banner.webp`;
            let freshBanner = false;
            if (!existsSync(cacheFile)) {
              await sharp(inputPath)
                .resize({ width: 400, withoutEnlargement: true })
                .webp({ quality: 85 })
                .toFile(cacheFile);
              freshBanner = true;
            }
            if (freshBanner || !existsSync(outFile)) copyFileSync(cacheFile, outFile);
            result = result.replace(originalTag, originalTag.replace(`src="${src}"`, `src="${outUrl}"`));
          } catch (e) {
            console.warn(`[image] Failed to optimize banner image ${src}: ${e.message}`);
          }
          continue;
        }

        // UI images (no-zoom): optimize to a logo-appropriate webp but keep the <img> tag intact.
        // No PhotoSwipe wrapper — these are logos, icons, decorative shapes, not content.
        // Output: 500px tall (2× retina for up to 250px CSS display), aspect ratio preserved.
        if ((before + after).includes("no-zoom")) {
          const ext = src.toLowerCase().split(".").pop();
          if (ext === "gif") continue;
          try {
            const siteOptDir = join(outputDir, "media/optimized");
            mkdirSync(siteOptDir, { recursive: true });
            mkdirSync(MEDIA_CACHE_DIR, { recursive: true });
            const baseName = decodeURIComponent(src.split("/").pop().replace(/\.[^.]+$/, ""));
            const cacheFile = join(MEDIA_CACHE_DIR, `${baseName}-nav.webp`);
            const outFile = join(siteOptDir, `${baseName}-nav.webp`);
            const outUrl = `/media/optimized/${encodeURIComponent(baseName)}-nav.webp`;
            let freshNav = false;
            if (!existsSync(cacheFile)) {
              await sharp(inputPath)
                .resize({ height: 500, withoutEnlargement: true })
                .webp({ quality: 85 })
                .toFile(cacheFile);
              freshNav = true;
            }
            if (freshNav || !existsSync(outFile)) copyFileSync(cacheFile, outFile);
            result = result.replace(originalTag, originalTag.replace(`src="${src}"`, `src="${outUrl}"`));
          } catch (e) {
            console.warn(`[image] Failed to optimize UI image ${src}: ${e.message}`);
          }
          continue;
        }

        // Extract alt text if present
        const altMatch = (before + after).match(/alt="([^"]*)"/);
        const alt = altMatch ? altMatch[1] : "";

        // Skip GIFs (preserve animation) and SVGs (vector, no raster conversion)
        const ext = src.toLowerCase().split(".").pop();
        if (ext === "gif" || ext === "svg") continue;

        try {
          // WebP for modern browsers (alpha preserved), PNG fallback for old browsers.
          // No JPEG — JPEG has no alpha channel and would make transparency black.
          const formats = mediaConfig.formats || ["webp", "png"];

          mkdirSync(MEDIA_CACHE_DIR, { recursive: true });
          const metadata = await Image(inputPath, {
            widths: mediaConfig.widths || [600, 1200],
            formats,
            outputDir: MEDIA_CACHE_DIR,
            urlPath: "/media/optimized/",
            filenameFormat: function (id, src, width, format) {
              const name = basename(src, extname(src));
              return `${name}-${width}w.${format}`;
            },
          });

          // Ensure generated files are also in _site/ for the current build.
          // Always overwrite — passthrough copy can race with sharp and create 0-byte
          // placeholders in _site/ before the real file is fully written to the cache.
          const siteOptDir = join(outputDir, "media/optimized");
          mkdirSync(siteOptDir, { recursive: true });
          for (const images of Object.values(metadata)) {
            for (const img of images) {
              const basename = img.url.split("/").pop();
              const siteFile = join(siteOptDir, basename);
              // Use img.outputPath (the actual written file) rather than a reconstructed path.
              // Reconstructed paths can miss on Windows if the cache dir is missing.
              const cachedFile = img.outputPath || join(MEDIA_CACHE_DIR, basename);
              if (existsSync(cachedFile)) copyFileSync(cachedFile, siteFile);
            }
          }

          const pictureHtml = Image.generateHTML(metadata, {
            alt,
            sizes: "(max-width: 600px) 100vw, 800px",
            loading: "lazy",
            decoding: "async",
          });

          // no-pswp: optimize but skip PhotoSwipe wrapper (e.g., images inside a Swiper gallery)
          if ((before + after).includes("no-pswp")) {
            result = result.replace(originalTag, pictureHtml);
            continue;
          }

          // Wrap in <a> for PhotoSwipe: dimensions from metadata, original path for full-res button
          const webpImages = metadata.webp || [];
          const allImages = webpImages.length > 0 ? webpImages : (metadata.png || []);
          const largest = allImages[allImages.length - 1];
          const pswpSrcset = webpImages.map((img) => `${img.url} ${img.width}w`).join(", ");

          const wrapped = [
            `<a class="pswp-gallery__item"`,
            ` href="${src}"`,
            ` data-pswp-src="${largest.url}"`,
            pswpSrcset ? ` data-pswp-srcset="${pswpSrcset}"` : "",
            ` data-pswp-width="${largest.width}"`,
            ` data-pswp-height="${largest.height}"`,
            ` data-original="${src}"`,
            `>`,
            pictureHtml,
            `</a>`,
          ].join("");

          result = result.replace(originalTag, wrapped);
        } catch (e) {
          // If image processing fails, keep original tag
          console.warn(`[image] Failed to optimize ${src}: ${e.message}`);
        }
      }
      return result;
    });

  // Visualizer build-time transform
  // Runs each visualizer's transform() on rendered HTML output.
  // Runtime-only visualizers (like checkbox-tracker) return content unchanged.
  // Build-time visualizers (future: timeline, recipe-card) modify HTML here.
  const buildTimeVisualizers = visualizers.filter(
    (v) => typeof v.transform === "function" && v.type !== "runtime",
  );

  if (buildTimeVisualizers.length > 0) {
    eleventyConfig.addTransform("visualizers", function (content) {
      if (!this.page.outputPath?.endsWith(".html")) return content;

      let result = content;
      for (const viz of buildTimeVisualizers) {
        result = viz.transform(result, { siteConfig });
      }
      return result;
    });
  }

  // Determine output directory and path prefix based on mount_path
  // e.g., mount_path: "marbles" → output to _site/marbles/, URLs start with /marbles/
  const mountPath = siteConfig.mount_path;
  const outputDir = mountPath ? `_site/${mountPath}` : "_site";
  const pathPrefix = mountPath ? `/${mountPath}/` : "/";

  if (mountPath) {
    console.log(`[eleventy] Mount path: /${mountPath}/ → output to ${outputDir}`);
  }

  // Run pagefind after every build (dev and prod) so search index is always current.
  // This replaces the build-site.js post-build step so both modes stay in sync.
  if (siteConfig.features?.search) {
    eleventyConfig.on("eleventy.after", () => {
      console.log("\n--- Building search index (Pagefind) ---");
      try {
        execSync(`npx pagefind --site ${outputDir}`, {
          stdio: "inherit",
          cwd: process.cwd(),
        });
        console.log("[pagefind] Search index built");
      } catch (e) {
        console.warn("[pagefind] Index build failed:", e.message);
      }
    });
  }

  return {
    dir: {
      input: SRC,
      includes: "_includes",
      data: "_data",
      output: outputDir,
    },
    pathPrefix,
    templateFormats: ["md", "njk"],
    markdownTemplateEngine: "njk",
  };
}
